### ISSUE TITLE
Create a function to compare versions

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/dependency-size#2]
The dependency can be defined with a "larger than" or "smaller than". such as `A>=1.0.2`, `B<2.1.1`. In order to satisfy these, we need to be able to compare version (e.g. `1.3.0 > 1.2.9` or `1.1.14 < 1.2.0`).

**Comment by dinhanhx** [comment]
We can take advantage of attribute `releases` of the response json because the list of attributes is sorted ascendingly. In other words, the version at the end is larger than the one at the start.
