### ISSUE TITLE
Create a dependency resolver

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/dependency-size#3]
Normally, we would install the latest stable package there is. However, there can be some package that require an obsolete package; for example `A` requires `B<=0.9.0`. In this case, install `0.9.0` release.

Sometimes we install 2 packages which require one package, but with different release specs. There can be 2 cases:

1. The two ranges overlap each other. E.g. `A` requires `B<=0.9.0` and `C` requires `B>=0.4.1`
2. The two ranges don't overlap each other. E.g. `A` requires `B<=0.9.0` and `C` requires `B>=0.10.5`

In the first case, we simply install the latest package that satisfy both dependency (in the example, 0.9.0). In the second case, install two versions (0.9.0 and the latest after 0.10.5).

**Comment by Huy-Ngo** [comment]
I'm not sure if this is related to graph so if you want, take a look at https://pypi.org/project/resolvelib/

**Comment by dinhanhx** [comment]
> In the second case, install two versions (0.9.0 and the latest after 0.10.5).

What do you mean by installing two versions?

**Comment by Huy-Ngo** [comment]
I explained it in the parentheses. What are you unclear about?

**Comment by dinhanhx** [comment]
The part "then later", it means "uninstalling 0.9.0 then installing the latest after 0.10.5" or "installing versions separately"?

**Comment by Huy-Ngo** [comment]
0.9.0 in this example is not installed. We need to installed both versions because two different packages require different versions. Where did I say anything about uninstalling?

**Comment by dinhanhx** [comment]
You didn't say anything about uninstalling. I have encountered the case that pip uninstall then install newer package then prompt "newer package may be incompatible"

**Comment by dinhanhx** [comment]
@Huy-Ngo you work on this
